### ISSUE TITLE
openapi をファイル分割する

### ISSUE THREAD

**Issue by sunakan** [sunabak0/akiyadego-openapi#17]
## 目的

- バラバラに実装しやすいようにするため
- treeコマンドなどで一覧しやすい
- コメントを記述する時、そこにフォーカスしやすくするため

## 方針

- リクエスト毎に分ける
  - path自体はフラットにするが、ディレクトリとする
  - HTTP メソッドでファイルを表現する（get__post.yml や post__post.ymlなど考えたが、ソートした時見づらいと考えた）
- レスポンスで利用するモデルは共通して使いたいので、別途分けて管理する（そして同じものを使う）
  - 無理に同じものを使う必要はない
  - RESTっぽくないリクエストで、そのURL特有のレスポンスの場合は、リクエストの方に一緒に記述する
- もしリクエストパラメータにバリデーションをつけることができるようになったら、共通化してファイルとして切り出す
- 例：（新規作成と更新時の）テキストの文字数は同じものを指しているはずなので、バリデーションも共通化したい

**Comment by sunakan** [comment]
OpenAPI Generator と相性悪い。。ぐぬぬ

**Comment by sunakan** [comment]
```shell
Caused by: java.lang.RuntimeException: Could not find openapi.yml#components/schemas/Post on the classpath

```

**Comment by sunakan** [comment]
OpenGenerator を優先すると Swagger UIのほうがうまく行かない

**Comment by sunakan** [comment]
Swagger UIを優先すると OpenAPI Generator のほうがうまく行かない

**Comment by sunakan** [comment]
merger 使ってうまくできないかな

**Comment by sunakan** [comment]
```yml
components:
  schemas:
    Post:
      $ref: './components/schemas/post.yml'
    PostResponse:
      $ref: './components/schemas/post-response.yml'
```

こんな風にして、post.yamlは


```yaml
post:
  required:
    - id
    - imagePath
```

は駄目(Post/Postとネストしてしまう）

```yml
required:
  - id
  - imagePath
```

とする必要がある

**Comment by sunakan** [comment]
```yml
components:
  schemas:
    Post:
      $ref: './components/schemas/post.yml'
    PostResponse:
      $ref: './components/schemas/post-response.yml'
```

だと、PostResponseクラスではなく、PostMinusResponseクラスができてしまう

=> ファイル名とクラス名は合わせるべきかも
